import requests

url = "http://127.0.0.1:8000/api/pokedex/"
pokemons = [
    {
        "id": 10,
        "nom": "Chenipan",
        "type_1": "Insecte",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 22.00,
        "discount": 5,
        "image": "img/010.png",
        "quantite": 100,
        "description": "Chenipan est un Pokémon de type Insecte de la première génération."
    },
    {
        "id": 11,
        "nom": "Chrysacier",
        "type_1": "Insecte",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/011.png",
        "quantite": 90,
        "description": "Chrysacier est l'évolution de Chenipan, un Pokémon de type Insecte."
    },
    {
        "id": 12,
        "nom": "Papilusion",
        "type_1": "Insecte",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 40.50,
        "discount": 5,
        "image": "img/012.png",
        "quantite": 75,
        "description": "Papilusion est l'évolution finale de Chenipan, de type Insecte et Vol."
    },
    {
        "id": 13,
        "nom": "Aspicot",
        "type_1": "Insecte",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 22.00,
        "discount": 5,
        "image": "img/013.png",
        "quantite": 100,
        "description": "Aspicot est un Pokémon de type Insecte et Poison de la première génération."
    },
    {
        "id": 14,
        "nom": "Coconfort",
        "type_1": "Insecte",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/014.png",
        "quantite": 90,
        "description": "Coconfort est l'évolution d'Aspicot, de type Insecte et Poison."
    },
    {
        "id": 15,
        "nom": "Dardargnan",
        "type_1": "Insecte",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/015.png",
        "quantite": 70,
        "description": "Dardargnan est l'évolution finale d'Aspicot, de type Insecte et Poison."
    },
    {
        "id": 16,
        "nom": "Roucool",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/016.png",
        "quantite": 95,
        "description": "Roucool est un Pokémon de type Normal et Vol de la première génération."
    },
    {
        "id": 17,
        "nom": "Roucoups",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/017.png",
        "quantite": 85,
        "description": "Roucoups est l'évolution de Roucool, un Pokémon de type Normal et Vol."
    },
    {
        "id": 18,
        "nom": "Roucarnage",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/018.png",
        "quantite": 60,
        "description": "Roucarnage est l'évolution finale de Roucool, un Pokémon puissant de type Normal et Vol."
    },
    {
        "id": 19,
        "nom": "Rattata",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 20.00,
        "discount": 5,
        "image": "img/019.png",
        "quantite": 100,
        "description": "Rattata est un Pokémon de type Normal, commun dans la première génération."
    },
    {
        "id": 20,
        "nom": "Rattatac",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/020.png",
        "quantite": 85,
        "description": "Rattatac est l'évolution de Rattata, un Pokémon de type Normal."
    },
    {
        "id": 21,
        "nom": "Piafabec",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 22.00,
        "discount": 5,
        "image": "img/021.png",
        "quantite": 100,
        "description": "Piafabec est un Pokémon de type Normal et Vol de la première génération."
    },
    {
        "id": 22,
        "nom": "Rapasdepic",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 40.00,
        "discount": 5,
        "image": "img/022.png",
        "quantite": 75,
        "description": "Rapasdepic est l'évolution de Piafabec, un Pokémon de type Normal et Vol."
    },
    {
        "id": 23,
        "nom": "Abo",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/023.png",
        "quantite": 90,
        "description": "Abo est un Pokémon de type Poison de la première génération."
    },
    {
        "id": 24,
        "nom": "Arbok",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 48.00,
        "discount": 5,
        "image": "img/024.png",
        "quantite": 70,
        "description": "Arbok est l'évolution d'Abo, un Pokémon de type Poison."
    },
        {
        "id": 26,
        "nom": "Raichu",
        "type_1": "Électrique",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 40.50,
        "discount": 5,
        "image": "img/026.png",
        "quantite": 75,
        "description": "Raichu est l'évolution de Pikachu, un Pokémon de type Électrique."
    },
    {
        "id": 27,
        "nom": "Sabelette",
        "type_1": "Sol",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/027.png",
        "quantite": 90,
        "description": "Sabelette est un Pokémon de type Sol de la première génération."
    },
    {
        "id": 28,
        "nom": "Sablaireau",
        "type_1": "Sol",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/028.png",
        "quantite": 70,
        "description": "Sablaireau est l'évolution de Sabelette, un Pokémon de type Sol."
    },
    {
        "id": 29,
        "nom": "Nidoran♀",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/029.png",
        "quantite": 95,
        "description": "Nidoran♀ est un Pokémon de type Poison de la première génération."
    },
    {
        "id": 30,
        "nom": "Nidorina",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/030.png",
        "quantite": 85,
        "description": "Nidorina est l'évolution de Nidoran♀, un Pokémon de type Poison."
    },
    {
        "id": 31,
        "nom": "Nidoqueen",
        "type_1": "Poison",
        "type_2": "Sol",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/031.png",
        "quantite": 60,
        "description": "Nidoqueen est l'évolution finale de Nidoran♀, de type Poison et Sol."
    },
    {
        "id": 32,
        "nom": "Nidoran♂",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/032.png",
        "quantite": 95,
        "description": "Nidoran♂ est un Pokémon de type Poison de la première génération."
    },
    {
        "id": 33,
        "nom": "Nidorino",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/033.png",
        "quantite": 85,
        "description": "Nidorino est l'évolution de Nidoran♂, un Pokémon de type Poison."
    },
    {
        "id": 34,
        "nom": "Nidoking",
        "type_1": "Poison",
        "type_2": "Sol",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/034.png",
        "quantite": 60,
        "description": "Nidoking est l'évolution finale de Nidoran♂, de type Poison et Sol."
    },
    {
        "id": 35,
        "nom": "Mélofée",
        "type_1": "Fée",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/035.png",
        "quantite": 90,
        "description": "Mélofée est un Pokémon de type Fée de la première génération."
    },
    {
        "id": 36,
        "nom": "Mélodelfe",
        "type_1": "Fée",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 5,
        "image": "img/036.png",
        "quantite": 65,
        "description": "Mélodelfe est l'évolution de Mélofée, un Pokémon de type Fée."
    },
    {
        "id": 37,
        "nom": "Goupix",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 32.00,
        "discount": 5,
        "image": "img/037.png",
        "quantite": 85,
        "description": "Goupix est un Pokémon de type Feu de la première génération."
    },
    {
        "id": 38,
        "nom": "Feunard",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 52.00,
        "discount": 10,
        "image": "img/038.png",
        "quantite": 50,
        "description": "Feunard est l'évolution de Goupix, un Pokémon de type Feu."
    },
    {
        "id": 39,
        "nom": "Rondoudou",
        "type_1": "Normal",
        "type_2": "Fée",
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/039.png",
        "quantite": 90,
        "description": "Rondoudou est un Pokémon de type Normal et Fée de la première génération."
    },
    {
        "id": 40,
        "nom": "Grodoudou",
        "type_1": "Normal",
        "type_2": "Fée",
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/040.png",
        "quantite": 70,
        "description": "Grodoudou est l'évolution de Rondoudou, un Pokémon de type Normal et Fée."
    },
    {
        "id": 41,
        "nom": "Nosferapti",
        "type_1": "Poison",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 22.00,
        "discount": 5,
        "image": "img/041.png",
        "quantite": 100,
        "description": "Nosferapti est un Pokémon de type Poison et Vol de la première génération."
    },
    {
        "id": 42,
        "nom": "Nosferalto",
        "type_1": "Poison",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 42.00,
        "discount": 5,
        "image": "img/042.png",
        "quantite": 75,
        "description": "Nosferalto est l'évolution de Nosferapti, un Pokémon de type Poison et Vol."
    },
    {
        "id": 43,
        "nom": "Mystherbe",
        "type_1": "Plante",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/043.png",
        "quantite": 95,
        "description": "Mystherbe est un Pokémon de type Plante et Poison de la première génération."
    },
        {
        "id": 44,
        "nom": "Ortide",
        "type_1": "Plante",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/044.png",
        "quantite": 85,
        "description": "Ortide est l'évolution de Mystherbe, un Pokémon de type Plante et Poison."
    },
    {
        "id": 45,
        "nom": "Rafflésia",
        "type_1": "Plante",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/045.png",
        "quantite": 60,
        "description": "Rafflésia est l'évolution finale de Mystherbe, un Pokémon de type Plante et Poison."
    },
    {
        "id": 46,
        "nom": "Paras",
        "type_1": "Insecte",
        "type_2": "Plante",
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/046.png",
        "quantite": 95,
        "description": "Paras est un Pokémon de type Insecte et Plante de la première génération."
    },
    {
        "id": 47,
        "nom": "Parasect",
        "type_1": "Insecte",
        "type_2": "Plante",
        "generation": 1,
        "legendaire": False,
        "prix": 40.00,
        "discount": 5,
        "image": "img/047.png",
        "quantite": 75,
        "description": "Parasect est l'évolution de Paras, un Pokémon de type Insecte et Plante."
    },
    {
        "id": 48,
        "nom": "Mimitoss",
        "type_1": "Insecte",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/048.png",
        "quantite": 90,
        "description": "Mimitoss est un Pokémon de type Insecte et Poison de la première génération."
    },
    {
        "id": 49,
        "nom": "Aéromite",
        "type_1": "Insecte",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/049.png",
        "quantite": 70,
        "description": "Aéromite est l'évolution de Mimitoss, un Pokémon de type Insecte et Poison."
    },
    {
        "id": 50,
        "nom": "Taupiqueur",
        "type_1": "Sol",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 22.00,
        "discount": 5,
        "image": "img/050.png",
        "quantite": 100,
        "description": "Taupiqueur est un Pokémon de type Sol de la première génération."
    },
    {
        "id": 51,
        "nom": "Triopikeur",
        "type_1": "Sol",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 40.00,
        "discount": 5,
        "image": "img/051.png",
        "quantite": 75,
        "description": "Triopikeur est l'évolution de Taupiqueur, un Pokémon de type Sol."
    },
    {
        "id": 52,
        "nom": "Miaouss",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/052.png",
        "quantite": 95,
        "description": "Miaouss est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 53,
        "nom": "Persian",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 42.00,
        "discount": 5,
        "image": "img/053.png",
        "quantite": 75,
        "description": "Persian est l'évolution de Miaouss, un Pokémon de type Normal."
    },
    {
        "id": 54,
        "nom": "Psykokwak",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/054.png",
        "quantite": 90,
        "description": "Psykokwak est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 55,
        "nom": "Akwakwak",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 48.00,
        "discount": 5,
        "image": "img/055.png",
        "quantite": 70,
        "description": "Akwakwak est l'évolution de Psykokwak, un Pokémon de type Eau."
    },
    {
        "id": 56,
        "nom": "Férosinge",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/056.png",
        "quantite": 90,
        "description": "Férosinge est un Pokémon de type Combat de la première génération."
    },
    {
        "id": 57,
        "nom": "Colossinge",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/057.png",
        "quantite": 70,
        "description": "Colossinge est l'évolution de Férosinge, un Pokémon de type Combat."
    },
    {
        "id": 58,
        "nom": "Caninos",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/058.png",
        "quantite": 85,
        "description": "Caninos est un Pokémon de type Feu de la première génération."
    },
    {
        "id": 59,
        "nom": "Arcanin",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/059.png",
        "quantite": 60,
        "description": "Arcanin est l'évolution de Caninos, un Pokémon de type Feu."
    },
    {
        "id": 60,
        "nom": "Ptitard",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/060.png",
        "quantite": 95,
        "description": "Ptitard est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 61,
        "nom": "Têtarte",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/061.png",
        "quantite": 85,
        "description": "Têtarte est l'évolution de Ptitard, un Pokémon de type Eau."
    },
    {
        "id": 62,
        "nom": "Tartard",
        "type_1": "Eau",
        "type_2": "Combat",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/062.png",
        "quantite": 60,
        "description": "Tartard est l'évolution finale de Ptitard, un Pokémon de type Eau et Combat."
    },
    {
        "id": 63,
        "nom": "Abra",
        "type_1": "Psy",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/063.png",
        "quantite": 90,
        "description": "Abra est un Pokémon de type Psy de la première génération."
    },
    {
        "id": 64,
        "nom": "Kadabra",
        "type_1": "Psy",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/064.png",
        "quantite": 70,
        "description": "Kadabra est l'évolution d'Abra, un Pokémon de type Psy."
    },
    {
        "id": 66,
        "nom": "Machoc",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/066.png",
        "quantite": 90,
        "description": "Machoc est un Pokémon de type Combat de la première génération."
    },
    {
        "id": 67,
        "nom": "Machopeur",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/067.png",
        "quantite": 70,
        "description": "Machopeur est l'évolution de Machoc, un Pokémon de type Combat."
    },
    {
        "id": 68,
        "nom": "Mackogneur",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/068.png",
        "quantite": 50,
        "description": "Mackogneur est l'évolution finale de Machoc, un Pokémon puissant de type Combat."
    },
    {
        "id": 69,
        "nom": "Chétiflor",
        "type_1": "Plante",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/069.png",
        "quantite": 95,
        "description": "Chétiflor est un Pokémon de type Plante et Poison de la première génération."
    },
    {
        "id": 70,
        "nom": "Boustiflor",
        "type_1": "Plante",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/070.png",
        "quantite": 85,
        "description": "Boustiflor est l'évolution de Chétiflor, un Pokémon de type Plante et Poison."
    },
    {
        "id": 71,
        "nom": "Empiflor",
        "type_1": "Plante",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/071.png",
        "quantite": 60,
        "description": "Empiflor est l'évolution finale de Chétiflor, un Pokémon de type Plante et Poison."
    },
    {
        "id": 72,
        "nom": "Tentacool",
        "type_1": "Eau",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/072.png",
        "quantite": 90,
        "description": "Tentacool est un Pokémon de type Eau et Poison de la première génération."
    },
    {
        "id": 73,
        "nom": "Tentacruel",
        "type_1": "Eau",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/073.png",
        "quantite": 60,
        "description": "Tentacruel est l'évolution de Tentacool, un Pokémon de type Eau et Poison."
    },
    {
        "id": 74,
        "nom": "Racaillou",
        "type_1": "Roche",
        "type_2": "Sol",
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/074.png",
        "quantite": 90,
        "description": "Racaillou est un Pokémon de type Roche et Sol de la première génération."
    },
    {
        "id": 75,
        "nom": "Gravalanch",
        "type_1": "Roche",
        "type_2": "Sol",
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/075.png",
        "quantite": 70,
        "description": "Gravalanch est l'évolution de Racaillou, un Pokémon de type Roche et Sol."
    },
    {
        "id": 76,
        "nom": "Grolem",
        "type_1": "Roche",
        "type_2": "Sol",
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/076.png",
        "quantite": 50,
        "description": "Grolem est l'évolution finale de Racaillou, un Pokémon puissant de type Roche et Sol."
    },
    {
        "id": 77,
        "nom": "Ponyta",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/077.png",
        "quantite": 90,
        "description": "Ponyta est un Pokémon de type Feu de la première génération."
    },
    {
        "id": 78,
        "nom": "Galopa",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/078.png",
        "quantite": 65,
        "description": "Galopa est l'évolution de Ponyta, un Pokémon de type Feu."
    },
    {
        "id": 79,
        "nom": "Ramoloss",
        "type_1": "Eau",
        "type_2": "Psy",
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/079.png",
        "quantite": 90,
        "description": "Ramoloss est un Pokémon de type Eau et Psy de la première génération."
    },
    {
        "id": 80,
        "nom": "Flagadoss",
        "type_1": "Eau",
        "type_2": "Psy",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/080.png",
        "quantite": 65,
        "description": "Flagadoss est l'évolution de Ramoloss, un Pokémon de type Eau et Psy."
    },
    {
        "id": 81,
        "nom": "Magnéti",
        "type_1": "Électrique",
        "type_2": "Acier",
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/081.png",
        "quantite": 90,
        "description": "Magnéti est un Pokémon de type Électrique et Acier de la première génération."
    },
    {
        "id": 82,
        "nom": "Magnéton",
        "type_1": "Électrique",
        "type_2": "Acier",
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/082.png",
        "quantite": 70,
        "description": "Magnéton est l'évolution de Magnéti, un Pokémon de type Électrique et Acier."
    },
    {
        "id": 83,
        "nom": "Canarticho",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/083.png",
        "quantite": 85,
        "description": "Canarticho est un Pokémon de type Normal et Vol de la première génération."
    },
    {
        "id": 84,
        "nom": "Doduo",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/084.png",
        "quantite": 90,
        "description": "Doduo est un Pokémon de type Normal et Vol de la première génération."
    },
    {
        "id": 85,
        "nom": "Dodrio",
        "type_1": "Normal",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/085.png",
        "quantite": 65,
        "description": "Dodrio est l'évolution de Doduo, un Pokémon de type Normal et Vol."
    },
    {
        "id": 86,
        "nom": "Otaria",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/086.png",
        "quantite": 90,
        "description": "Otaria est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 87,
        "nom": "Lamantine",
        "type_1": "Eau",
        "type_2": "Glace",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/087.png",
        "quantite": 65,
        "description": "Lamantine est l'évolution d'Otaria, un Pokémon de type Eau et Glace."
    },
    {
        "id": 88,
        "nom": "Tadmorv",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/088.png",
        "quantite": 90,
        "description": "Tadmorv est un Pokémon de type Poison de la première génération."
    },
    {
        "id": 89,
        "nom": "Grotadmorv",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/089.png",
        "quantite": 65,
        "description": "Grotadmorv est l'évolution de Tadmorv, un Pokémon de type Poison."
    },
    {
        "id": 90,
        "nom": "Kokiyas",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/090.png",
        "quantite": 90,
        "description": "Kokiyas est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 91,
        "nom": "Crustabri",
        "type_1": "Eau",
        "type_2": "Glace",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/091.png",
        "quantite": 65,
        "description": "Crustabri est l'évolution de Kokiyas, un Pokémon de type Eau et Glace."
    },
    {
        "id": 92,
        "nom": "Fantominus",
        "type_1": "Spectre",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/092.png",
        "quantite": 90,
        "description": "Fantominus est un Pokémon de type Spectre et Poison de la première génération."
    },
    {
        "id": 93,
        "nom": "Spectrum",
        "type_1": "Spectre",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/093.png",
        "quantite": 70,
        "description": "Spectrum est l'évolution de Fantominus, un Pokémon de type Spectre et Poison."
    },
    {
        "id": 94,
        "nom": "Ectoplasma",
        "type_1": "Spectre",
        "type_2": "Poison",
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/094.png",
        "quantite": 50,
        "description": "Ectoplasma est l'évolution finale de Fantominus, un Pokémon puissant de type Spectre et Poison."
    },
    {
        "id": 95,
        "nom": "Onix",
        "type_1": "Roche",
        "type_2": "Sol",
        "generation": 1,
        "legendaire": False,
        "prix": 40.00,
        "discount": 5,
        "image": "img/095.png",
        "quantite": 75,
        "description": "Onix est un Pokémon de type Roche et Sol de la première génération."
    },
    {
        "id": 96,
        "nom": "Soporifik",
        "type_1": "Psy",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/096.png",
        "quantite": 90,
        "description": "Soporifik est un Pokémon de type Psy de la première génération."
    },
    {
        "id": 97,
        "nom": "Hypnomade",
        "type_1": "Psy",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/097.png",
        "quantite": 70,
        "description": "Hypnomade est l'évolution de Soporifik, un Pokémon de type Psy."
    },
    {
        "id": 98,
        "nom": "Krabby",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/098.png",
        "quantite": 90,
        "description": "Krabby est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 99,
        "nom": "Krabboss",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/099.png",
        "quantite": 65,
        "description": "Krabboss est l'évolution de Krabby, un Pokémon de type Eau."
    },
    {
        "id": 100,
        "nom": "Voltorbe",
        "type_1": "Électrique",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/100.png",
        "quantite": 90,
        "description": "Voltorbe est un Pokémon de type Électrique de la première génération."
    },
    {
        "id": 101,
        "nom": "Électrode",
        "type_1": "Électrique",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/101.png",
        "quantite": 70,
        "description": "Électrode est l'évolution de Voltorbe, un Pokémon de type Électrique."
    },
    {
        "id": 102,
        "nom": "Noeunoeuf",
        "type_1": "Plante",
        "type_2": "Psy",
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/102.png",
        "quantite": 90,
        "description": "Noeunoeuf est un Pokémon de type Plante et Psy de la première génération."
    },
    {
        "id": 103,
        "nom": "Noadkoko",
        "type_1": "Plante",
        "type_2": "Psy",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/103.png",
        "quantite": 65,
        "description": "Noadkoko est l'évolution de Noeunoeuf, un Pokémon de type Plante et Psy."
    },
    {
        "id": 104,
        "nom": "Osselait",
        "type_1": "Sol",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/104.png",
        "quantite": 90,
        "description": "Osselait est un Pokémon de type Sol de la première génération."
    },
    {
        "id": 105,
        "nom": "Ossatueur",
        "type_1": "Sol",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/105.png",
        "quantite": 65,
        "description": "Ossatueur est l'évolution d'Osselait, un Pokémon de type Sol."
    },
    {
        "id": 106,
        "nom": "Kicklee",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/106.png",
        "quantite": 65,
        "description": "Kicklee est un Pokémon de type Combat de la première génération."
    },
    {
        "id": 107,
        "nom": "Tygnon",
        "type_1": "Combat",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/107.png",
        "quantite": 65,
        "description": "Tygnon est un Pokémon de type Combat de la première génération."
    },
    {
        "id": 108,
        "nom": "Excelangue",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 40.00,
        "discount": 5,
        "image": "img/108.png",
        "quantite": 75,
        "description": "Excelangue est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 109,
        "nom": "Smogo",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/109.png",
        "quantite": 90,
        "description": "Smogo est un Pokémon de type Poison de la première génération."
    },
    {
        "id": 110,
        "nom": "Smogogo",
        "type_1": "Poison",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/110.png",
        "quantite": 65,
        "description": "Smogogo est l'évolution de Smogo, un Pokémon de type Poison."
    },
    {
        "id": 111,
        "nom": "Rhinocorne",
        "type_1": "Sol",
        "type_2": "Roche",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/111.png",
        "quantite": 85,
        "description": "Rhinocorne est un Pokémon de type Sol et Roche de la première génération."
    },
    {
        "id": 112,
        "nom": "Rhinoféros",
        "type_1": "Sol",
        "type_2": "Roche",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/112.png",
        "quantite": 60,
        "description": "Rhinoféros est l'évolution de Rhinocorne, un Pokémon de type Sol et Roche."
    },
    {
        "id": 113,
        "nom": "Leveinard",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/113.png",
        "quantite": 50,
        "description": "Leveinard est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 114,
        "nom": "Saquedeneu",
        "type_1": "Plante",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/114.png",
        "quantite": 85,
        "description": "Saquedeneu est un Pokémon de type Plante de la première génération."
    },
    {
        "id": 115,
        "nom": "Kangourex",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/115.png",
        "quantite": 65,
        "description": "Kangourex est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 116,
        "nom": "Hypotrempe",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/116.png",
        "quantite": 90,
        "description": "Hypotrempe est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 117,
        "nom": "Hypocéan",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/117.png",
        "quantite": 70,
        "description": "Hypocéan est l'évolution d'Hypotrempe, un Pokémon de type Eau."
    },
    {
        "id": 118,
        "nom": "Poissirène",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/118.png",
        "quantite": 90,
        "description": "Poissirène est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 119,
        "nom": "Poissoroy",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 45.00,
        "discount": 5,
        "image": "img/119.png",
        "quantite": 70,
        "description": "Poissoroy est l'évolution de Poissirène, un Pokémon de type Eau."
    },
    {
        "id": 120,
        "nom": "Stari",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 28.00,
        "discount": 5,
        "image": "img/120.png",
        "quantite": 90,
        "description": "Stari est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 121,
        "nom": "Staross",
        "type_1": "Eau",
        "type_2": "Psy",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/121.png",
        "quantite": 65,
        "description": "Staross est l'évolution de Stari, un Pokémon de type Eau et Psy."
    },
    {
        "id": 122,
        "nom": "M. Mime",
        "type_1": "Psy",
        "type_2": "Fée",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/122.png",
        "quantite": 65,
        "description": "M. Mime est un Pokémon de type Psy et Fée de la première génération."
    },
    {
        "id": 123,
        "nom": "Insécateur",
        "type_1": "Insecte",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/123.png",
        "quantite": 65,
        "description": "Insécateur est un Pokémon de type Insecte et Vol de la première génération."
    },
    {
        "id": 124,
        "nom": "Lippoutou",
        "type_1": "Glace",
        "type_2": "Psy",
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/124.png",
        "quantite": 65,
        "description": "Lippoutou est un Pokémon de type Glace et Psy de la première génération."
    },
    {
        "id": 125,
        "nom": "Élektek",
        "type_1": "Électrique",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/125.png",
        "quantite": 65,
        "description": "Élektek est un Pokémon de type Électrique de la première génération."
    },
    {
        "id": 126,
        "nom": "Magmar",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/126.png",
        "quantite": 65,
        "description": "Magmar est un Pokémon de type Feu de la première génération."
    },
    {
        "id": 127,
        "nom": "Scarabrute",
        "type_1": "Insecte",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/127.png",
        "quantite": 65,
        "description": "Scarabrute est un Pokémon de type Insecte de la première génération."
    },
    {
        "id": 128,
        "nom": "Tauros",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/128.png",
        "quantite": 65,
        "description": "Tauros est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 129,
        "nom": "Magicarpe",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 25.00,
        "discount": 5,
        "image": "img/129.png",
        "quantite": 95,
        "description": "Magicarpe est un Pokémon de type Eau de la première génération."
    },
    {
        "id": 130,
        "nom": "Léviator",
        "type_1": "Eau",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/130.png",
        "quantite": 50,
        "description": "Léviator est l'évolution de Magicarpe, un Pokémon de type Eau et Vol."
    },
    {
        "id": 131,
        "nom": "Lokhlass",
        "type_1": "Eau",
        "type_2": "Glace",
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/131.png",
        "quantite": 50,
        "description": "Lokhlass est un Pokémon de type Eau et Glace de la première génération."
    },
    {
        "id": 132,
        "nom": "Métamorph",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/132.png",
        "quantite": 65,
        "description": "Métamorph est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 133,
        "nom": "Évoli",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 30.00,
        "discount": 5,
        "image": "img/133.png",
        "quantite": 90,
        "description": "Évoli est un Pokémon de type Normal de la première génération, connu pour ses nombreuses évolutions."
    },
    {
        "id": 134,
        "nom": "Aquali",
        "type_1": "Eau",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/134.png",
        "quantite": 65,
        "description": "Aquali est l'une des évolutions d'Évoli, un Pokémon de type Eau."
    },
    {
        "id": 135,
        "nom": "Voltali",
        "type_1": "Électrique",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/135.png",
        "quantite": 65,
        "description": "Voltali est l'une des évolutions d'Évoli, un Pokémon de type Électrique."
    },
    {
        "id": 136,
        "nom": "Pyroli",
        "type_1": "Feu",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/136.png",
        "quantite": 65,
        "description": "Pyroli est l'une des évolutions d'Évoli, un Pokémon de type Feu."
    },
    {
        "id": 137,
        "nom": "Porygon",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 50.00,
        "discount": 10,
        "image": "img/137.png",
        "quantite": 65,
        "description": "Porygon est un Pokémon de type Normal de la première génération."
    },
    {
        "id": 138,
        "nom": "Amonita",
        "type_1": "Roche",
        "type_2": "Eau",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/138.png",
        "quantite": 85,
        "description": "Amonita est un Pokémon de type Roche et Eau de la première génération."
    },
    {
        "id": 139,
        "nom": "Amonistar",
        "type_1": "Roche",
        "type_2": "Eau",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/139.png",
        "quantite": 60,
        "description": "Amonistar est l'évolution d'Amonita, un Pokémon de type Roche et Eau."
    },
    {
        "id": 140,
        "nom": "Kabuto",
        "type_1": "Roche",
        "type_2": "Eau",
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/140.png",
        "quantite": 85,
        "description": "Kabuto est un Pokémon de type Roche et Eau de la première génération."
    },
    {
        "id": 141,
        "nom": "Kabutops",
        "type_1": "Roche",
        "type_2": "Eau",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/141.png",
        "quantite": 60,
        "description": "Kabutops est l'évolution de Kabuto, un Pokémon de type Roche et Eau."
    },
    {
        "id": 142,
        "nom": "Ptéra",
        "type_1": "Roche",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/142.png",
        "quantite": 60,
        "description": "Ptéra est un Pokémon de type Roche et Vol de la première génération."
    },
    {
        "id": 143,
        "nom": "Ronflex",
        "type_1": "Normal",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 60.00,
        "discount": 10,
        "image": "img/143.png",
        "quantite": 50,
        "description": "Ronflex est un Pokémon de type Normal, célèbre pour sa grande taille et son sommeil."
    },
        {
        "id": 144,
        "nom": "Artikodin",
        "type_1": "Glace",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": True,
        "prix": 70.00,
        "discount": 15,
        "image": "img/144.png",
        "quantite": 40,
        "description": "Artikodin est un Pokémon légendaire de type Glace et Vol."
    },
    {
        "id": 145,
        "nom": "Électhor",
        "type_1": "Électrique",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": True,
        "prix": 70.00,
        "discount": 15,
        "image": "img/145.png",
        "quantite": 40,
        "description": "Électhor est un Pokémon légendaire de type Électrique et Vol."
    },
    {
        "id": 146,
        "nom": "Sulfura",
        "type_1": "Feu",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": True,
        "prix": 70.00,
        "discount": 15,
        "image": "img/146.png",
        "quantite": 40,
        "description": "Sulfura est un Pokémon légendaire de type Feu et Vol."
    },
    {
        "id": 147,
        "nom": "Minidraco",
        "type_1": "Dragon",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 35.00,
        "discount": 5,
        "image": "img/147.png",
        "quantite": 85,
        "description": "Minidraco est un Pokémon de type Dragon de la première génération."
    },
    {
        "id": 148,
        "nom": "Draco",
        "type_1": "Dragon",
        "type_2": None,
        "generation": 1,
        "legendaire": False,
        "prix": 55.00,
        "discount": 10,
        "image": "img/148.png",
        "quantite": 60,
        "description": "Draco est l'évolution de Minidraco, un Pokémon de type Dragon."
    },
    {
        "id": 149,
        "nom": "Dracolosse",
        "type_1": "Dragon",
        "type_2": "Vol",
        "generation": 1,
        "legendaire": False,
        "prix": 65.00,
        "discount": 10,
        "image": "img/149.png",
        "quantite": 50,
        "description": "Dracolosse est l'évolution finale de Minidraco, un puissant Pokémon de type Dragon et Vol."
    }
]



for pokemon in pokemons:
    response = requests.post(url, json=pokemon)
    print(response.status_code, response.json())