# Generated by Django 5.1.1 on 2024-09-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telephone', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('mdp', models.CharField(max_length=150)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=150)),
                ('code_postal', models.IntegerField()),
                ('livraison', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('numero_commande', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur')),
            ],
        ),
    ]
